# Generated by Django 5.2.3 on 2025-08-09 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_initial'),
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='products.product'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_items', to='products.supplier'),
        ),
        migrations.AddField(
            model_name='stockitemtracking',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockitemtracking',
            name='stock_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking', to='stock.stockitem'),
        ),
        migrations.AddField(
            model_name='stockitemtracking',
            name='location_from',
            field=models.ForeignKey(blank=True, help_text='specific to movement_type=transfer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_from', to='stock.stocklocation'),
        ),
        migrations.AddField(
            model_name='stockitemtracking',
            name='location_to',
            field=models.ForeignKey(blank=True, help_text='specific to movement_type=transfer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_to', to='stock.stocklocation'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='stock_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_items', to='stock.stocklocation'),
        ),
    ]
