# Generated by Django 5.2.3 on 2025-08-17 12:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='stockitemtracking',
            name='movement_type',
            field=models.CharField(choices=[('stock_added', 'Stock Added'), ('stock_removed', 'Stock Removed'), ('update', 'Update'), ('transfer', 'Transfer'), ('sale', 'Sale'), ('stock_increase', 'Stock Increase'), ('stock_decrease', 'Stock Decrease')], max_length=20),
        ),
    ]
