# Generated by Django 5.2.3 on 2025-08-09 07:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total sale amount after discount.', max_digits=10)),
                ('discount_applied', models.BooleanField(default=False, help_text='Indicates if a discount was applied.')),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Discount amount applied to the sale.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('partially_returned', 'Partially returned'), ('fully_returned', 'Fully returned')], default='completed', help_text='Status of the sale for returns/refunds.', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('quantity', models.PositiveIntegerField(help_text='Quantity sold from this StockItem.', validators=[django.core.validators.MinValueValidator(1)])),
                ('sale_price', models.DecimalField(decimal_places=2, help_text='Price per unit at the time of sale.', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
    ]
