# Generated by Django 5.2.3 on 2025-08-09 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_initial'),
        ('sales', '0001_initial'),
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who performed the sale (e.g., cashier).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(help_text='Product sold (for reference if StockItem is deleted).', on_delete=django.db.models.deletion.CASCADE, related_name='sale_items', to='products.product'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(help_text='Sale this item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='sale_items', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='stock_item',
            field=models.ForeignKey(help_text='StockItem batch sold.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items', to='stock.stockitem'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['created_at'], name='sales_sale_created_e208b3_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['created_by'], name='sales_sale_created_e9263a_idx'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['sale'], name='sales_salei_sale_id_413ea3_idx'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['stock_item'], name='sales_salei_stock_i_247df5_idx'),
        ),
    ]
